import type { MetadataRoute } from "next";

// AI bot policy — generated by ~/Projects/apply-robots-ai-block-nextjs.js
// Blocks training crawlers (heavy bandwidth, no traffic) but keeps real-time
// response bots allowed (so the site stays referenced in live LLM answers).

const TRAINING_BOTS = [
  "GPTBot",
  "ClaudeBot",
  "anthropic-ai",
  "Claude-Web",
  "Bytespider",
  "CCBot",
  "Meta-ExternalAgent",
  "FacebookBot",
  "cohere-ai",
  "Google-Extended",
  "Applebot-Extended",
  "Diffbot",
  "ImagesiftBot",
  "Omgili",
  "omgilibot"
];

const SCRAPER_BOTS = [
  "AhrefsBot",
  "SemrushBot",
  "MJ12bot",
  "PetalBot",
  "DotBot",
  "BLEXBot",
  "DataForSeoBot"
];

const REALTIME_BOTS = [
  "ChatGPT-User",
  "OAI-SearchBot",
  "PerplexityBot",
  "Perplexity-User",
  "YouBot",
  "DuckAssistBot",
  "MistralAI-User"
];

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: [
        "/api/",
        "/_next/",
      ],
      },
      ...TRAINING_BOTS.map((userAgent) => ({ userAgent, disallow: "/" })),
      ...SCRAPER_BOTS.map((userAgent) => ({ userAgent, disallow: "/" })),
      ...REALTIME_BOTS.map((userAgent) => ({ userAgent, allow: "/" })),
    ],
    sitemap: "https://sxmprivatechef.com/sitemap.xml",
  };
}
